# Generated by Django 4.1.1 on 2022-09-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='post',
            field=models.TextField(default='Administrator'),
        ),
    ]
