# Generated by Django 4.0 on 2022-10-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0002_alter_customuser_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.TextField()),
                ('briefInfo', models.TextField()),
                ('photo', models.ImageField(default=None, upload_to='wanted/')),
                ('detailInfo', models.TextField()),
                ('isPublished', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='secretcodes',
            name='post',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post',
            field=models.TextField(default='User'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
