# Generated by Django 4.0 on 2022-10-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_wantedpersons_secretcodes_post_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecretCodes',
            new_name='SecretCode',
        ),
        migrations.RenameModel(
            old_name='WantedPersons',
            new_name='WantedPerson',
        ),
    ]
