# Generated by Django 4.1.1 on 2022-09-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.TextField(default='admin'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.TextField(default='admin'),
        ),
    ]
