# Generated by Django 4.0 on 2022-10-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_secretcodes_secretcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='post',
            field=models.TextField(default='Administrator'),
        ),
    ]
