# Generated by Django 4.0 on 2022-10-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_customuser_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='post',
            field=models.TextField(default='Director'),
        ),
    ]
