# Generated by Django 4.1.2 on 2022-10-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_customuser_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author', models.TextField()),
                ('post', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post',
            field=models.TextField(default='User'),
        ),
        migrations.AlterField(
            model_name='secretcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wantedperson',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
