# Generated by Django 4.1.3 on 2022-11-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_role_delete_comment_remove_customuser_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
