# Generated by Django 4.1.3 on 2022-12-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='warnings',
        ),
    ]
